packages:
  - packages/*
  - agent
  - subgraph
  - web

patchedDependencies:
  '@graphprotocol/graph-ts@0.33.0': patches/@graphprotocol__graph-ts@0.33.0.patch

allowBuilds:
  esbuild: true
  sharp: true
